<h3 style="margin-bottom: 0; background: <?= $title['backgroundColor']; ?>;color: #ffffff;padding: 5px;" class="monolog-output"><?=$title['time']; ?> - <?=$title['title']; ?></h3>
<table cellspacing="1" width="100%" class="monolog-output">
    <tr style="padding: 4px;text-align: left;">
        <th style="vertical-align: top;background: #ccc;color: #000" width="100">
            Message
        </th>
        <td style="padding: 4px;text-align: left;vertical-align: top;background: #eee;color: #000">
            <?= $message; ?>
        </td>
    </tr>
<?php if ($matchResults) : ?>
    <?php foreach ($matchResults as $matchResult) : ?>
    <?php $mock = $matchResult->getMock(); ?>
    <tr style="padding: 4px;text-align: left;">
        <th style="vertical - align: top;background: #ccc;color: #000" width="100">localhost:<?=$mock->getPort(); ?></th>
        <td style="padding: 4px;text-align: left;vertical-align: top;background: #eee;color: #000">
            <?= $mock->getFile(); ?> : <?= $mock->getLine(); ?><br />
        <?php foreach ($matchResult->getTermResults() as $termResult) : ?>
            <div style="text-decoration: underline"><?= (string)$termResult->getTerm(); ?> assertion</div>
            <pre> <?= \PHPUnit\Framework\TestFailure::exceptionToString($termResult->getException()); ?></pre>
        <?php endforeach;?>
        </td>
     </tr>
    <?php endforeach;?>
<?php endif;?>

</table>